# generated by datamodel-codegen:
#   filename:  0.DOIP_Op.Hello-Response.json
#   version:   0.30.1

from __future__ import annotations

from typing import Any, Dict, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, conint


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    serviceName: Optional[str] = Field(
        None, description='the name of the DOIP service.'
    )
    serviceDescription: Optional[str] = Field(
        None, description='the description of the service.'
    )
    ipAddress: str = Field(..., description='the IP address of the service.')
    port: conint(ge=0, le=65535) = Field(
        ..., description='the listening port on the IP address.'
    )
    protocol: str = Field(..., description='the default shall be ‘TCP’.')
    protocolVersion: str = Field(
        ..., description='highest version of the DOIP protocol supported.'
    )
    publicKey: Union[Dict[str, Any], str]


class Output(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='id: the identifier of the DO.')
    type: Literal['0.TYPE/DOIPServiceInfo', 'DOIPServiceInfo'] = Field(
        ...,
        description='type: the DO type. Must be 0.TYPE/DO or its extension. See Types section.',
    )
    attributes: Attributes = Field(
        ...,
        description='attributes: one or more fields (key-value pairs) serialized as a JSON (sub) object.',
    )


class HelloResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: Optional[str] = Field(
        None,
        description='requestId: the identifier of the request to which this is a response. The DOIP service must include in its response the requestId provided by the client.',
    )
    status: Literal['0.DOIP/Status.001'] = Field(
        ...,
        description='status: an identifier that indicates the status of the request. Status codes shall have associated unique identifiers resolvable as specified in the IRP.',
    )
    output: Output
