# generated by datamodel-codegen:
#   filename:  0.DOIP_Op.Update-Request.json
#   version:   0.30.1

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class Authentication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    username: str
    password: str


class Authentication1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token: str


class Authentication2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str


class Element(BaseModel):
    id: Optional[str] = Field(
        None, description='id: identifier of the element; must be unique within a DO.'
    )
    length: Optional[str] = Field(None, description='length of the data portion.')
    type: Optional[str] = Field(
        None, description='shall be a type as defined in this spec or a MIME type'
    )
    attributes: Optional[Dict[str, Any]] = Field(
        None,
        description='one or more fields serialized as an object using the default serialization, or as a JSON (sub) object.',
    )


class DoipDoSerialization(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='id: the identifier of the DO.')
    type: str = Field(
        ...,
        description='type: the DO type. Must be 0.TYPE/DO or its extension. See Types section.',
    )
    attributes: Optional[Dict[str, Any]] = Field(
        None,
        description='attributes: one or more fields (key-value pairs) serialized as a JSON (sub) object.',
    )
    elements: Optional[List[Element]] = Field(
        None,
        description='description: one or more elements serialized as an array in the default serialization, with each element consisting of',
    )
    signatures: Optional[str] = Field(
        None,
        description='Required for DOs of type 0.TYPE/DOIPServiceInfo and 0.TYPE/DOIPOperation; otherwise optional. The field is an array of strings in the default serialization; each string is in JWS format19 with an unencoded detached payload.',
    )


class UpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: Optional[str] = Field(
        None,
        description='requestId: the identifier of the request provided by the client; shall be unique within a given DOIP session so clients can distinguish between DOIP service responses. The requestId shall be a string not exceeding 4096 bits.',
    )
    clientId: Optional[str] = Field(
        None, description='clientId: the identifier of the client.'
    )
    targetId: str = Field(
        ...,
        description='targetId: the identifier of the DO on which the operation is to be invoked; the DOIP service could itself be the target.',
    )
    operationId: Literal['0.DOIP/Op.Update'] = Field(
        ..., description='operationId: the identifier of the operation to be performed.'
    )
    authentication: Optional[
        Union[Authentication, Authentication1, Authentication2]
    ] = Field(
        None,
        description='authentication: optional JSON object used by clients to authenticate.',
    )
    input: Optional[DoipDoSerialization] = Field(
        None,
        description="Input: a serialized digital object. The default serialization may be used if the object lacks element data; otherwise the serialization is a multi-segment DO serialization as described above. The 'id' can be omitted to ask the DOIP service to automatically choose the id.",
    )
